name: Build SM8650 Kernel
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Proton Clang
        run: |
          wget https://github.com/kdrag0n/proton-clang/releases/download/2024.04.03/proton-clang-2024.04.03.tar.zst
          mkdir clang
          tar --zstd -xf proton-clang-2024.04.03.tar.zst -C clang
          echo "$GITHUB_WORKSPACE/clang/bin" >> $GITHUB_PATH

      - name: Compile
        run: |
          export ARCH=arm64
          make O=out s24_defconfig
          make O=out -j$(nproc) LLVM=1 LLVM_IAS=1

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: kernel-out
          path: out/arch/arm64/boot
