concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Build SM8650 Samsung GKI Kernel
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 拉取内核源码
        uses: actions/checkout@v4

      - name: 安装编译依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev bison flex libelf-dev git python3 gcc-aarch64-linux-gnu

      - name: 清理旧编译
        run: |
          make mrproper

      - name: gki_defconfig
        run: |
          export ARCH=arm64
          make gki_defconfig

      - name: 编译内核 -j2
        run: |
          export ARCH=arm64
          make CROSS_COMPILE=aarch64-linux-gnu- -j2

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: kernel-output
          path: |
            arch/arm64/boot/Image
            arch/arm64/boot/dts/vendor/qcom/
